### ISSUE TITLE
'tbmodels' command not found after ‘pip install aiida-tbmodels’

### ISSUE THREAD

**Issue by JiaweiHuang48** [greschd/aiida-tbmodels#20]
Dear Dominik,

I am new to aiida and I am still struggling to run my very first wannierization calculation.

It seems that I cannot determine the abs_path for 'tbmodels' while setting up the code. 
There has no 'tbmodels' command in ~/.../env/aiida/bin/ and no response with 'which tbmodels' even if I successfully installed (and reinstalled) aiida-tbmodels with pip.

However, I did find tbmodel plugins in aiida.calculations after a reentry scan
* tbmodels.eigenvals
* tbmodels.parse
* tbmodels.slice
* tbmodels.symmetrize

Do you have any clue about this?

btw, I am working with aiida-core1.6.8

Thank you

bests

**Comment by greschd** [comment]
Yes, that is expected behavior: the `aiida-tbmodels` package contains only the AiiDA plugin, not the TBmodels code itself.

You will have to install that separately, with `pip install tbmodels`. This can be in a separate virtual environment from where AiiDA runs.

**Comment by toby459** [comment]
Thank you so much, I just fixed the above problem following your suggestion.

**Comment by JiaweiHuang48** [comment]
> Yes, that is expected behavior: the `aiida-tbmodels` package contains only the AiiDA plugin, not the TBmodels code itself.
> 
> You will have to install that separately, with `pip install tbmodels`. This can be in a separate virtual environment from where AiiDA runs.


Thank you so much, I just fixed the above problem following your suggestion.
